app = "autoedit-v3"

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 10000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

  [[services.http_checks]]
  interval = 10000
  method = "get"
  path = "/api/health"
  timeout = 2000
